-- Underwater
greenery_galore.register_plantlike_rooted_plant({
	name = "123test",
	desc = "123test",
	bounds = {-.3, -.5, -.3, .3, -0.20, .3},
	biomes = {"taiga_ocean",
               "snowy_grassland_ocean",
               "grassland_ocean",
               "coniferous_forest_ocean",
               "deciduous_forest_ocean",
               "sandstone_desert_ocean",
               "cold_desert_ocean"},
	spawn_on = {"default:sand"},
	persist = 2.1,
	scale = 1.2,
	spawn_by = {"default:water_source"},
	density = .60,
	spread = 40,
	place_offset_y = -1,
	y_max = -5,
	y_min = -10,
	min_height = 48,
	max_height = 96,
	base = "default:sand",
	base_image = "default_sand.png"
})
-- Plants on shore
greenery_galore.register_plantlike_plant({
	name = "myosotis_palustris",
	desc = "Myosotis Palustris",
	color = "cyan",
	scale = 1.2,
	waving = 1,
	randomRotate = true,
	bounds = {-.3, -.5, -.3, .3, 0.6, .3},
	biomes = {"grassland_ocean",
               "rainforest_ocean",
               "rainforest_swamp",
               "savanna_shore",
               "deciduous_forest_shore",
               "savanna_ocean",
               "rainforest_ocean",
               "grassland",
               "deciduous_forest",
               "coniferous_forest"},
	spawn_on = {"default:dirt_with_grass"},
	spawn_by = {"default:water_source"},
	num_spawn_by = 2,
	persist = 1.5,
	density = 0.15,
	spread = 10,
	y_min = -2
})

greenery_galore.register_plantlike_plant({
	name = "cattail_reeds",
	desc = "Cattail Reeds",
	color = "brown",
	scale = 3.2,
	bounds = {-.3, -.5, -.3, .3, 0.6, .3},
	biomes = {"grassland_ocean",
               "rainforest_ocean","rainforest_swamp",
               "savanna_shore",
               "deciduous_forest_shore",
               "savanna_ocean",
               "rainforest_ocean",
               "grassland",
               "deciduous_forest",
               "coniferous_forest",
               "rainforest"},
	spawn_on = {"default:dirt_with_grass","default:dirt_with_rainforest_litter"},
	spawn_by = {"default:water_source"},
	num_spawn_by = 0,
	specialDraw = 1,
	persist = 1.4,
	density = 0.14,
	spread = 500,
	y_max = 1
})

-- Waterlilies
greenery_galore.register_nodebox_plant({
	name = "waterlily",
	desc = "Large Waterlily",
	color = "green",
	randomRotate = true,
	bounds = {-0.5, -0.45, -0.5, 0.5, -0.48, 0.5},
	persist = 0.05,
	density = 0.31,
	spread = 1,
	biomes = {"grassland_ocean",
               "rainforest_ocean",
               "rainforest_swamp",
               "savanna_shore",
               "deciduous_forest_shore",
               "savanna_ocean",
               "rainforest_ocean",},
	spawn_on = {"default:dirt"},
	liquids_pointable = true,
	waterPlace = true,
	place_offset_y = 1,
	walkable = true,
	y_min = -5
})

greenery_galore.register_mesh_plant({
	name = "white_waterlily",
	desc = "Blooming White Waterlily",
	mesh = "waterlily.obj",
	color = "white",
	randomRotate = true,
	waving = 1,
	bounds = {-0.4, -0.45, -0.4, 0.4, -0.48, 0.4},
	persist = 1.8,
	density = 0.02,
	spread = 100,
	biomes = {"grassland_ocean",
               "rainforest_ocean",
               "rainforest_swamp",
               "savanna_shore",
               "deciduous_forest_shore",
               "savanna_ocean",
               "rainforest_ocean",},
	spawn_on = {"default:dirt"},
	liquids_pointable = true,
	waterPlace = true,
	place_offset_y = 1,
	inv_image  = "greenery_galore_white_waterlily_inv.png",
	wield_image = "greenery_galore_white_waterlily_inv.png",
	y_min = -5
})
